POST http://127.0.0.1:8000/api/auth-token/
Content-Type: application/json

{
    "username": "admin@admin.com",
    "password": "admin"
}


###
GET http://127.0.0.1:8000/api/product/v1/list/
# retrieve list of all products with thier category child
# can search, filter fields

###
GET http://127.0.0.1:8000/api/product/v1/retrieve/1

###
# filter by attribute(get products have attribute matrial is wood)

GET http://127.0.0.1:8000/api/product/v1/list/?weight=10kg


###

### Get Orders (Requires Authentication)
GET http://127.0.0.1:8000/api/order/v1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzU2OTgwLCJpYXQiOjE3NTUzMjQ5ODAsImp0aSI6ImI2YzBhYjJkMTRjMzQyYjlhYTNhZTE3ZjZiNTFiZWI5IiwidXNlcl9pZCI6M30.VGEIer0o8zEaIFLlYdOxx127vEhPHCBOfDx0uS4sRDs
Accept: application/json

### Create Order (Requires Authentication)
POST http://127.0.0.1:8000/api/order/v1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzU2OTgwLCJpYXQiOjE3NTUzMjQ5ODAsImp0aSI6ImI2YzBhYjJkMTRjMzQyYjlhYTNhZTE3ZjZiNTFiZWI5IiwidXNlcl9pZCI6M30.VGEIer0o8zEaIFLlYdOxx127vEhPHCBOfDx0uS4sRDs
Content-Type: application/json
Accept: application/json

{
    "items": [
      {
        "id": 1,
        "product": 1,
        "quantity": 1,
        "price": "80000.00",
        "variation": 1
      }
    ],
    "payments": [
      {
        "amount": "500",
        "payment_method": "gateway",
        "transaction_id": "7398909987",
        "status": "pending",
        "created_at": "2025-04-30T06:04:42.160158Z"
      }
    ],
    "shipping": {
      "tracking_number": "324242",
      "carrier": "Post",
      "estimated_delivery": "2025-04-30",
      "shipped_at": "2025-04-30T06:03:29Z",
      "delivered_at": null
    },
    "order_number": "3242343242",
    "status": "pending",
    "shipping_address": "tehran, iran",
    "billing_address": "karaj, Iran",
    "phone": "+989201502830",
    "note": "Call when you arrived",
    "created_at": "2025-04-30T05:57:44.977068Z",
    "updated_at": "2025-04-30T06:29:34.121983Z",
    "total_amount": "60000.00"
  }

###

PATCH http://127.0.0.1:8000/api/order/v1/1/
Authorization: Token 50721b8673fb8d4a9d9933fa966d7ba5a63b73fc
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "product": 1,
            "variation": 1,
            "quantity": 1,
            "price": 9000000
        }
    ]
}

###
GET http://127.0.0.1:8000/api/cart/
Authorization: Token 50721b8673fb8d4a9d9933fa966d7ba5a63b73fc
Content-Type: application/json
Accept: application/json

###
PATCH http://127.0.0.1:8000/api/cart/
Authorization: Token 50721b8673fb8d4a9d9933fa966d7ba5a63b73fc
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "product": 1,
            "variation": 1,
            "quantity": 1
        }
    ]
}
