# Generated by Django 5.2 on 2025-04-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="price_modifier",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="stock",
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_modifier",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.attributevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "attribute")},
            },
        ),
    ]
