# Generated by Django 5.2 on 2025-04-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_categories_productcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-is_featured',)},
        ),
    ]
