# Generated by Django 5.2 on 2025-04-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="attribute",
            new_name="variation",
        ),
    ]
