# Generated by Django 5.2 on 2025-04-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_rename_attribute_cartitem_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.SmallIntegerField(default=1),
        ),
    ]
