# Generated by Django 5.2 on 2025-04-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_quantity"),
        ("product", "0004_alter_productattribute_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productvariation",
            ),
        ),
    ]
