# Generated by Django 5.2 on 2025-04-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="attribute",
            new_name="variation",
        ),
    ]
